Added model number argument

diff --git a/scripts/bash/autobuild_ b/scripts/bash/autobuild_
--- a/scripts/bash/autobuild_
+++ b/scripts/bash/autobuild_
@@ -4,37 +4,52 @@
 # $3 task build folder
 # $4 result output folder
 # $5 filepath to constraints
-# $6 only-bin-file: 'output' all-project-files: '*'
+# $6 only bin file => 'output'
+#    all project files => '*'
+# $7 tcl arguments
 
-# Clear auto_build folder
-rm -rf .autobuild/*
+LOG_FILE="run.log"
 
-# Make directories for Vivado
-mkdir .autobuild/input_srcs
-mkdir .autobuild/input_srcs/srcs
-mkdir .autobuild/input_srcs/constraints
-mkdir .autobuild/vivado_project
-mkdir .autobuild/output
-mkdir .autobuild/tcl_script
+log_message() {
+    echo "$(date '+%d.%m.%Y %H:%M') - $1" >> "$LOG_FILE"
+}
 
-# Copy constraints into auto_build folder
-cp "$5" .autobuild/input_srcs/constraints
+log_message "Clearing auto_build folder..."
+rm -rf /home/"$1"/.autobuild/* 2>> "$LOG_FILE"
 
-# Copy build folder
-cp -r "$3" .autobuild/input_srcs/srcs
+log_message "Creating directories for Vivado..."
+mkdir -p /home/"$1"/.autobuild/input_srcs/srcs 2>> "$LOG_FILE"
+mkdir -p /home/"$1"/.autobuild/input_srcs/constraints 2>> "$LOG_FILE"
+mkdir -p /home/"$1"/.autobuild/vivado_project 2>> "$LOG_FILE"
+mkdir -p /home/"$1"/.autobuild/output 2>> "$LOG_FILE"
+mkdir -p /home/"$1"/.autobuild/tcl_script 2>> "$LOG_FILE"
 
-# Let Vivado run
+log_message "Copying constraints..."
+cp "$5" /home/"$1"/.autobuild/input_srcs/constraints 2>> "$LOG_FILE"
+
+log_message "Copying build folder..."
+cp -r "$3" /home/"$1"/.autobuild/input_srcs/srcs 2>> "$LOG_FILE"
+
+log_message "Running Vivado..."
 export XILINXD_LICENSE_FILE=/opt/flexlm/Xilinx.lic
-/tools/Xilinx/Vivado/2021.1/bin/vivado -mode tcl -source "$2" >> "$4/run.log" 2>&1
+/tools/Xilinx/Vivado/2021.1/bin/vivado -mode tcl -source "$2" -tclargs "$7" >> "$LOG_FILE" 2>&1
 
-# Copy *bin file to output folder
-cp .autobuild/vivado_project/project_1.runs/impl_1/*.bin .autobuild/output/
+if [ $? -ne 0 ]; then
+    log_message "Vivado run failed. Please check the log for errors."
+    exit 1
+fi
 
-# Copy script in folder
-cp .autobuild_script/create_project_full_run.tcl .autobuild/tcl_script/
+log_message "Copying bin files to output folder..."
+cp /home/"$1"/.autobuild/vivado_project/project_1.runs/impl_1/*.bin /home/"$1"/.autobuild/output/ 2>> "$LOG_FILE"
 
-# Copy output folder to result folder
-cp -r .autobuild/"$6" "$4"
+log_message "Copying the script to the folder..."
+cp /home/"$1"/.autobuild_script/create_project_full_run.tcl /home/"$1"/.autobuild/tcl_script/ 2>> "$LOG_FILE"
 
-# Clear auto_build folder
-rm -rf .autobuild/*
+log_message "Copying output folder to result folder..."
+# shellcheck disable=SC2086
+cp -r /home/"$1"/.autobuild/$6 "$4" 2>> "$LOG_FILE"
+
+log_message "Clearing auto_build folder..."
+rm -rf /home/"$1"/.autobuild/* 2>> "$LOG_FILE"
+
+log_message "Script completed successfully."
